# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dservice.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64service.proto\x12\x04\x44\x41TA\"\x19\n\x06Result\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x13\n\x04\x44\x61ta\x12\x0b\n\x03msg\x18\x01 \x01(\t\";\n\x08StoreReq\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"\x18\n\x08Passcode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\".\n\x08UserPass\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t2\xde\x01\n\x02\x44\x42\x12,\n\x0cRegisterUser\x12\x0e.DATA.UserPass\x1a\x0c.DATA.Result\x12)\n\tStoreData\x12\x0e.DATA.StoreReq\x1a\x0c.DATA.Result\x12%\n\x07GetData\x12\x0e.DATA.UserPass\x1a\n.DATA.Data\x12-\n\x0bGenPasscode\x12\x0e.DATA.UserPass\x1a\x0e.DATA.Passcode\x12)\n\x0bGetAuthData\x12\x0e.DATA.Passcode\x1a\n.DATA.Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULT']._serialized_start=24
  _globals['_RESULT']._serialized_end=49
  _globals['_DATA']._serialized_start=51
  _globals['_DATA']._serialized_end=70
  _globals['_STOREREQ']._serialized_start=72
  _globals['_STOREREQ']._serialized_end=131
  _globals['_PASSCODE']._serialized_start=133
  _globals['_PASSCODE']._serialized_end=157
  _globals['_USERPASS']._serialized_start=159
  _globals['_USERPASS']._serialized_end=205
  _globals['_DB']._serialized_start=208
  _globals['_DB']._serialized_end=430
# @@protoc_insertion_point(module_scope)
