# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dservice_pb2 as dservice__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/DATA.DB/RegisterUser',
                request_serializer=dservice__pb2.UserPass.SerializeToString,
                response_deserializer=dservice__pb2.Result.FromString,
                _registered_method=True)
        self.StoreData = channel.unary_unary(
                '/DATA.DB/StoreData',
                request_serializer=dservice__pb2.StoreReq.SerializeToString,
                response_deserializer=dservice__pb2.Result.FromString,
                _registered_method=True)
        self.GenPasscode = channel.unary_unary(
                '/DATA.DB/GenPasscode',
                request_serializer=dservice__pb2.UserPass.SerializeToString,
                response_deserializer=dservice__pb2.Passcode.FromString,
                _registered_method=True)
        self.GetData = channel.unary_unary(
                '/DATA.DB/GetData',
                request_serializer=dservice__pb2.UserPass.SerializeToString,
                response_deserializer=dservice__pb2.Data.FromString,
                _registered_method=True)
        self.GetAuthData = channel.unary_unary(
                '/DATA.DB/GetAuthData',
                request_serializer=dservice__pb2.Passcode.SerializeToString,
                response_deserializer=dservice__pb2.Data.FromString,
                _registered_method=True)


class DBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenPasscode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=dservice__pb2.UserPass.FromString,
                    response_serializer=dservice__pb2.Result.SerializeToString,
            ),
            'StoreData': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreData,
                    request_deserializer=dservice__pb2.StoreReq.FromString,
                    response_serializer=dservice__pb2.Result.SerializeToString,
            ),
            'GenPasscode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenPasscode,
                    request_deserializer=dservice__pb2.UserPass.FromString,
                    response_serializer=dservice__pb2.Passcode.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=dservice__pb2.UserPass.FromString,
                    response_serializer=dservice__pb2.Data.SerializeToString,
            ),
            'GetAuthData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthData,
                    request_deserializer=dservice__pb2.Passcode.FromString,
                    response_serializer=dservice__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DATA.DB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DATA.DB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DATA.DB/RegisterUser',
            dservice__pb2.UserPass.SerializeToString,
            dservice__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DATA.DB/StoreData',
            dservice__pb2.StoreReq.SerializeToString,
            dservice__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenPasscode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DATA.DB/GenPasscode',
            dservice__pb2.UserPass.SerializeToString,
            dservice__pb2.Passcode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DATA.DB/GetData',
            dservice__pb2.UserPass.SerializeToString,
            dservice__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DATA.DB/GetAuthData',
            dservice__pb2.Passcode.SerializeToString,
            dservice__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
